CREATE TABLE `Country` (
  `id` int(11) UNSIGNED NOT NULL auto_increment,
  `code` smallint(6) default NULL,
  `iso3166a1` char(2) default NULL,
  `iso3166a2` char(3) default NULL,
  `nombre` varchar(128) default NULL,
  PRIMARY KEY  (`id`)
)  ;

INSERT INTO `Country` VALUES (1, 4, 'AF', 'AFG', 'Afganistán');
INSERT INTO `Country` VALUES (2, 248, 'AX', 'ALA', 'Islas Gland');
INSERT INTO `Country` VALUES (3, 8, 'AL', 'ALB', 'Albania');
INSERT INTO `Country` VALUES (4, 276, 'DE', 'DEU', 'Alemania');
INSERT INTO `Country` VALUES (5, 20, 'AD', 'AND', 'Andorra');
INSERT INTO `Country` VALUES (6, 24, 'AO', 'AGO', 'Angola');
INSERT INTO `Country` VALUES (7, 660, 'AI', 'AIA', 'Anguilla');
INSERT INTO `Country` VALUES (8, 10, 'AQ', 'ATA', 'Antártida');
INSERT INTO `Country` VALUES (9, 28, 'AG', 'ATG', 'Antigua y Barbuda');
INSERT INTO `Country` VALUES (10, 530, 'AN', 'ANT', 'Antillas Holandesas');
INSERT INTO `Country` VALUES (11, 682, 'SA', 'SAU', 'Arabia Saudí');
INSERT INTO `Country` VALUES (12, 12, 'DZ', 'DZA', 'Argelia');
INSERT INTO `Country` VALUES (13, 32, 'AR', 'ARG', 'Argentina');
INSERT INTO `Country` VALUES (14, 51, 'AM', 'ARM', 'Armenia');
INSERT INTO `Country` VALUES (15, 533, 'AW', 'ABW', 'Aruba');
INSERT INTO `Country` VALUES (16, 36, 'AU', 'AUS', 'Australia');
INSERT INTO `Country` VALUES (17, 40, 'AT', 'AUT', 'Austria');
INSERT INTO `Country` VALUES (18, 31, 'AZ', 'AZE', 'Azerbaiyán');
INSERT INTO `Country` VALUES (19, 44, 'BS', 'BHS', 'Bahamas');
INSERT INTO `Country` VALUES (20, 48, 'BH', 'BHR', 'Bahréin');
INSERT INTO `Country` VALUES (21, 50, 'BD', 'BGD', 'Bangladesh');
INSERT INTO `Country` VALUES (22, 52, 'BB', 'BRB', 'Barbados');
INSERT INTO `Country` VALUES (23, 112, 'BY', 'BLR', 'Bielorrusia');
INSERT INTO `Country` VALUES (24, 56, 'BE', 'BEL', 'Bélgica');
INSERT INTO `Country` VALUES (25, 84, 'BZ', 'BLZ', 'Belice');
INSERT INTO `Country` VALUES (26, 204, 'BJ', 'BEN', 'Benin');
INSERT INTO `Country` VALUES (27, 60, 'BM', 'BMU', 'Bermudas');
INSERT INTO `Country` VALUES (28, 64, 'BT', 'BTN', 'Bhután');
INSERT INTO `Country` VALUES (29, 68, 'BO', 'BOL', 'Bolivia');
INSERT INTO `Country` VALUES (30, 70, 'BA', 'BIH', 'Bosnia y Herzegovina');
INSERT INTO `Country` VALUES (31, 72, 'BW', 'BWA', 'Botsuana');
INSERT INTO `Country` VALUES (32, 74, 'BV', 'BVT', 'Isla Bouvet');
INSERT INTO `Country` VALUES (33, 76, 'BR', 'BRA', 'Brasil');
INSERT INTO `Country` VALUES (34, 96, 'BN', 'BRN', 'Brunéi');
INSERT INTO `Country` VALUES (35, 100, 'BG', 'BGR', 'Bulgaria');
INSERT INTO `Country` VALUES (36, 854, 'BF', 'BFA', 'Burkina Faso');
INSERT INTO `Country` VALUES (37, 108, 'BI', 'BDI', 'Burundi');
INSERT INTO `Country` VALUES (38, 132, 'CV', 'CPV', 'Cabo Verde');
INSERT INTO `Country` VALUES (39, 136, 'KY', 'CYM', 'Islas Caimán');
INSERT INTO `Country` VALUES (40, 116, 'KH', 'KHM', 'Camboya');
INSERT INTO `Country` VALUES (41, 120, 'CM', 'CMR', 'Camerún');
INSERT INTO `Country` VALUES (42, 124, 'CA', 'CAN', 'Canadá');
INSERT INTO `Country` VALUES (43, 140, 'CF', 'CAF', 'República Centroafricana');
INSERT INTO `Country` VALUES (44, 148, 'TD', 'TCD', 'Chad');
INSERT INTO `Country` VALUES (45, 203, 'CZ', 'CZE', 'República Checa');
INSERT INTO `Country` VALUES (46, 152, 'CL', 'CHL', 'Chile');
INSERT INTO `Country` VALUES (47, 156, 'CN', 'CHN', 'China');
INSERT INTO `Country` VALUES (48, 196, 'CY', 'CYP', 'Chipre');
INSERT INTO `Country` VALUES (49, 162, 'CX', 'CXR', 'Isla de Navidad');
INSERT INTO `Country` VALUES (50, 336, 'VA', 'VAT', 'Ciudad del Vaticano');
INSERT INTO `Country` VALUES (51, 166, 'CC', 'CCK', 'Islas Cocos');
INSERT INTO `Country` VALUES (52, 170, 'CO', 'COL', 'Colombia');
INSERT INTO `Country` VALUES (53, 174, 'KM', 'COM', 'Comoras');
INSERT INTO `Country` VALUES (54, 180, 'CD', 'COD', 'República Democrática del Congo');
INSERT INTO `Country` VALUES (55, 178, 'CG', 'COG', 'Congo');
INSERT INTO `Country` VALUES (56, 184, 'CK', 'COK', 'Islas Cook');
INSERT INTO `Country` VALUES (57, 408, 'KP', 'PRK', 'Corea del Norte');
INSERT INTO `Country` VALUES (58, 410, 'KR', 'KOR', 'Corea del Sur');
INSERT INTO `Country` VALUES (59, 384, 'CI', 'CIV', 'Costa de Marfil');
INSERT INTO `Country` VALUES (60, 188, 'CR', 'CRI', 'Costa Rica');
INSERT INTO `Country` VALUES (61, 191, 'HR', 'HRV', 'Croacia');
INSERT INTO `Country` VALUES (62, 192, 'CU', 'CUB', 'Cuba');
INSERT INTO `Country` VALUES (63, 208, 'DK', 'DNK', 'Dinamarca');
INSERT INTO `Country` VALUES (64, 212, 'DM', 'DMA', 'Dominica');
INSERT INTO `Country` VALUES (65, 214, 'DO', 'DOM', 'República Dominicana');
INSERT INTO `Country` VALUES (66, 218, 'EC', 'ECU', 'Ecuador');
INSERT INTO `Country` VALUES (67, 818, 'EG', 'EGY', 'Egipto');
INSERT INTO `Country` VALUES (68, 222, 'SV', 'SLV', 'El Salvador');
INSERT INTO `Country` VALUES (69, 784, 'AE', 'ARE', 'Emiratos Árabes Unidos');
INSERT INTO `Country` VALUES (70, 232, 'ER', 'ERI', 'Eritrea');
INSERT INTO `Country` VALUES (71, 703, 'SK', 'SVK', 'Eslovaquia');
INSERT INTO `Country` VALUES (72, 705, 'SI', 'SVN', 'Eslovenia');
INSERT INTO `Country` VALUES (73, 724, 'ES', 'ESP', 'España');
INSERT INTO `Country` VALUES (74, 581, 'UM', 'UMI', 'Islas ultramarinas de Estados Unidos');
INSERT INTO `Country` VALUES (75, 840, 'US', 'USA', 'Estados Unidos');
INSERT INTO `Country` VALUES (76, 233, 'EE', 'EST', 'Estonia');
INSERT INTO `Country` VALUES (77, 231, 'ET', 'ETH', 'Etiopía');
INSERT INTO `Country` VALUES (78, 234, 'FO', 'FRO', 'Islas Feroe');
INSERT INTO `Country` VALUES (79, 608, 'PH', 'PHL', 'Filipinas');
INSERT INTO `Country` VALUES (80, 246, 'FI', 'FIN', 'Finlandia');
INSERT INTO `Country` VALUES (81, 242, 'FJ', 'FJI', 'Fiyi');
INSERT INTO `Country` VALUES (82, 250, 'FR', 'FRA', 'Francia');
INSERT INTO `Country` VALUES (83, 266, 'GA', 'GAB', 'Gabón');
INSERT INTO `Country` VALUES (84, 270, 'GM', 'GMB', 'Gambia');
INSERT INTO `Country` VALUES (85, 268, 'GE', 'GEO', 'Georgia');
INSERT INTO `Country` VALUES (86, 239, 'GS', 'SGS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO `Country` VALUES (87, 288, 'GH', 'GHA', 'Ghana');
INSERT INTO `Country` VALUES (88, 292, 'GI', 'GIB', 'Gibraltar');
INSERT INTO `Country` VALUES (89, 308, 'GD', 'GRD', 'Granada');
INSERT INTO `Country` VALUES (90, 300, 'GR', 'GRC', 'Grecia');
INSERT INTO `Country` VALUES (91, 304, 'GL', 'GRL', 'Groenlandia');
INSERT INTO `Country` VALUES (92, 312, 'GP', 'GLP', 'Guadalupe');
INSERT INTO `Country` VALUES (93, 316, 'GU', 'GUM', 'Guam');
INSERT INTO `Country` VALUES (94, 320, 'GT', 'GTM', 'Guatemala');
INSERT INTO `Country` VALUES (95, 254, 'GF', 'GUF', 'Guayana Francesa');
INSERT INTO `Country` VALUES (96, 324, 'GN', 'GIN', 'Guinea');
INSERT INTO `Country` VALUES (97, 226, 'GQ', 'GNQ', 'Guinea Ecuatorial');
INSERT INTO `Country` VALUES (98, 624, 'GW', 'GNB', 'Guinea-Bissau');
INSERT INTO `Country` VALUES (99, 328, 'GY', 'GUY', 'Guyana');
INSERT INTO `Country` VALUES (100, 332, 'HT', 'HTI', 'Haití');
INSERT INTO `Country` VALUES (101, 334, 'HM', 'HMD', 'Islas Heard y McDonald');
INSERT INTO `Country` VALUES (102, 340, 'HN', 'HND', 'Honduras');
INSERT INTO `Country` VALUES (103, 344, 'HK', 'HKG', 'Hong Kong');
INSERT INTO `Country` VALUES (104, 348, 'HU', 'HUN', 'Hungría');
INSERT INTO `Country` VALUES (105, 356, 'IN', 'IND', 'India');
INSERT INTO `Country` VALUES (106, 360, 'ID', 'IDN', 'Indonesia');
INSERT INTO `Country` VALUES (107, 364, 'IR', 'IRN', 'Irán');
INSERT INTO `Country` VALUES (108, 368, 'IQ', 'IRQ', 'Iraq');
INSERT INTO `Country` VALUES (109, 372, 'IE', 'IRL', 'Irlanda');
INSERT INTO `Country` VALUES (110, 352, 'IS', 'ISL', 'Islandia');
INSERT INTO `Country` VALUES (111, 376, 'IL', 'ISR', 'Israel');
INSERT INTO `Country` VALUES (112, 380, 'IT', 'ITA', 'Italia');
INSERT INTO `Country` VALUES (113, 388, 'JM', 'JAM', 'Jamaica');
INSERT INTO `Country` VALUES (114, 392, 'JP', 'JPN', 'Japón');
INSERT INTO `Country` VALUES (115, 400, 'JO', 'JOR', 'Jordania');
INSERT INTO `Country` VALUES (116, 398, 'KZ', 'KAZ', 'Kazajstán');
INSERT INTO `Country` VALUES (117, 404, 'KE', 'KEN', 'Kenia');
INSERT INTO `Country` VALUES (118, 417, 'KG', 'KGZ', 'Kirguistán');
INSERT INTO `Country` VALUES (119, 296, 'KI', 'KIR', 'Kiribati');
INSERT INTO `Country` VALUES (120, 414, 'KW', 'KWT', 'Kuwait');
INSERT INTO `Country` VALUES (121, 418, 'LA', 'LAO', 'Laos');
INSERT INTO `Country` VALUES (122, 426, 'LS', 'LSO', 'Lesotho');
INSERT INTO `Country` VALUES (123, 428, 'LV', 'LVA', 'Letonia');
INSERT INTO `Country` VALUES (124, 422, 'LB', 'LBN', 'Líbano');
INSERT INTO `Country` VALUES (125, 430, 'LR', 'LBR', 'Liberia');
INSERT INTO `Country` VALUES (126, 434, 'LY', 'LBY', 'Libia');
INSERT INTO `Country` VALUES (127, 438, 'LI', 'LIE', 'Liechtenstein');
INSERT INTO `Country` VALUES (128, 440, 'LT', 'LTU', 'Lituania');
INSERT INTO `Country` VALUES (129, 442, 'LU', 'LUX', 'Luxemburgo');
INSERT INTO `Country` VALUES (130, 446, 'MO', 'MAC', 'Macao');
INSERT INTO `Country` VALUES (131, 807, 'MK', 'MKD', 'ARY Macedonia');
INSERT INTO `Country` VALUES (132, 450, 'MG', 'MDG', 'Madagascar');
INSERT INTO `Country` VALUES (133, 458, 'MY', 'MYS', 'Malasia');
INSERT INTO `Country` VALUES (134, 454, 'MW', 'MWI', 'Malawi');
INSERT INTO `Country` VALUES (135, 462, 'MV', 'MDV', 'Maldivas');
INSERT INTO `Country` VALUES (136, 466, 'ML', 'MLI', 'Malí');
INSERT INTO `Country` VALUES (137, 470, 'MT', 'MLT', 'Malta');
INSERT INTO `Country` VALUES (138, 238, 'FK', 'FLK', 'Islas Malvinas');
INSERT INTO `Country` VALUES (139, 580, 'MP', 'MNP', 'Islas Marianas del Norte');
INSERT INTO `Country` VALUES (140, 504, 'MA', 'MAR', 'Marruecos');
INSERT INTO `Country` VALUES (141, 584, 'MH', 'MHL', 'Islas Marshall');
INSERT INTO `Country` VALUES (142, 474, 'MQ', 'MTQ', 'Martinica');
INSERT INTO `Country` VALUES (143, 480, 'MU', 'MUS', 'Mauricio');
INSERT INTO `Country` VALUES (144, 478, 'MR', 'MRT', 'Mauritania');
INSERT INTO `Country` VALUES (145, 175, 'YT', 'MYT', 'Mayotte');
INSERT INTO `Country` VALUES (146, 484, 'MX', 'MEX', 'México');
INSERT INTO `Country` VALUES (147, 583, 'FM', 'FSM', 'Micronesia');
INSERT INTO `Country` VALUES (148, 498, 'MD', 'MDA', 'Moldavia');
INSERT INTO `Country` VALUES (149, 492, 'MC', 'MCO', 'Mónaco');
INSERT INTO `Country` VALUES (150, 496, 'MN', 'MNG', 'Mongolia');
INSERT INTO `Country` VALUES (151, 500, 'MS', 'MSR', 'Montserrat');
INSERT INTO `Country` VALUES (152, 508, 'MZ', 'MOZ', 'Mozambique');
INSERT INTO `Country` VALUES (153, 104, 'MM', 'MMR', 'Myanmar');
INSERT INTO `Country` VALUES (154, 516, 'NA', 'NAM', 'Namibia');
INSERT INTO `Country` VALUES (155, 520, 'NR', 'NRU', 'Nauru');
INSERT INTO `Country` VALUES (156, 524, 'NP', 'NPL', 'Nepal');
INSERT INTO `Country` VALUES (157, 558, 'NI', 'NIC', 'Nicaragua');
INSERT INTO `Country` VALUES (158, 562, 'NE', 'NER', 'Níger');
INSERT INTO `Country` VALUES (159, 566, 'NG', 'NGA', 'Nigeria');
INSERT INTO `Country` VALUES (160, 570, 'NU', 'NIU', 'Niue');
INSERT INTO `Country` VALUES (161, 574, 'NF', 'NFK', 'Isla Norfolk');
INSERT INTO `Country` VALUES (162, 578, 'NO', 'NOR', 'Noruega');
INSERT INTO `Country` VALUES (163, 540, 'NC', 'NCL', 'Nueva Caledonia');
INSERT INTO `Country` VALUES (164, 554, 'NZ', 'NZL', 'Nueva Zelanda');
INSERT INTO `Country` VALUES (165, 512, 'OM', 'OMN', 'Omán');
INSERT INTO `Country` VALUES (166, 528, 'NL', 'NLD', 'Países Bajos');
INSERT INTO `Country` VALUES (167, 586, 'PK', 'PAK', 'Pakistán');
INSERT INTO `Country` VALUES (168, 585, 'PW', 'PLW', 'Palau');
INSERT INTO `Country` VALUES (169, 275, 'PS', 'PSE', 'Palestina');
INSERT INTO `Country` VALUES (170, 591, 'PA', 'PAN', 'Panamá');
INSERT INTO `Country` VALUES (171, 598, 'PG', 'PNG', 'Papúa Nueva Guinea');
INSERT INTO `Country` VALUES (172, 600, 'PY', 'PRY', 'Paraguay');
INSERT INTO `Country` VALUES (173, 604, 'PE', 'PER', 'Perú');
INSERT INTO `Country` VALUES (174, 612, 'PN', 'PCN', 'Islas Pitcairn');
INSERT INTO `Country` VALUES (175, 258, 'PF', 'PYF', 'Polinesia Francesa');
INSERT INTO `Country` VALUES (176, 616, 'PL', 'POL', 'Polonia');
INSERT INTO `Country` VALUES (177, 620, 'PT', 'PRT', 'Portugal');
INSERT INTO `Country` VALUES (178, 630, 'PR', 'PRI', 'Puerto Rico');
INSERT INTO `Country` VALUES (179, 634, 'QA', 'QAT', 'Qatar');
INSERT INTO `Country` VALUES (180, 826, 'GB', 'GBR', 'Reino Unido');
INSERT INTO `Country` VALUES (181, 638, 'RE', 'REU', 'Reunión');
INSERT INTO `Country` VALUES (182, 646, 'RW', 'RWA', 'Ruanda');
INSERT INTO `Country` VALUES (183, 642, 'RO', 'ROU', 'Rumania');
INSERT INTO `Country` VALUES (184, 643, 'RU', 'RUS', 'Rusia');
INSERT INTO `Country` VALUES (185, 732, 'EH', 'ESH', 'Sahara Occidental');
INSERT INTO `Country` VALUES (186, 90, 'SB', 'SLB', 'Islas Salomón');
INSERT INTO `Country` VALUES (187, 882, 'WS', 'WSM', 'Samoa');
INSERT INTO `Country` VALUES (188, 16, 'AS', 'ASM', 'Samoa Americana');
INSERT INTO `Country` VALUES (189, 659, 'KN', 'KNA', 'San Cristóbal y Nevis');
INSERT INTO `Country` VALUES (190, 674, 'SM', 'SMR', 'San Marino');
INSERT INTO `Country` VALUES (191, 666, 'PM', 'SPM', 'San Pedro y Miquelón');
INSERT INTO `Country` VALUES (192, 670, 'VC', 'VCT', 'San Vicente y las Granadinas');
INSERT INTO `Country` VALUES (193, 654, 'SH', 'SHN', 'Santa Helena');
INSERT INTO `Country` VALUES (194, 662, 'LC', 'LCA', 'Santa Lucía');
INSERT INTO `Country` VALUES (195, 678, 'ST', 'STP', 'Santo Tomé y Príncipe');
INSERT INTO `Country` VALUES (196, 686, 'SN', 'SEN', 'Senegal');
INSERT INTO `Country` VALUES (197, 891, 'CS', 'SCG', 'Serbia y Montenegro');
INSERT INTO `Country` VALUES (198, 690, 'SC', 'SYC', 'Seychelles');
INSERT INTO `Country` VALUES (199, 694, 'SL', 'SLE', 'Sierra Leona');
INSERT INTO `Country` VALUES (200, 702, 'SG', 'SGP', 'Singapur');
INSERT INTO `Country` VALUES (201, 760, 'SY', 'SYR', 'Siria');
INSERT INTO `Country` VALUES (202, 706, 'SO', 'SOM', 'Somalia');
INSERT INTO `Country` VALUES (203, 144, 'LK', 'LKA', 'Sri Lanka');
INSERT INTO `Country` VALUES (204, 748, 'SZ', 'SWZ', 'Suazilandia');
INSERT INTO `Country` VALUES (205, 710, 'ZA', 'ZAF', 'Sudáfrica');
INSERT INTO `Country` VALUES (206, 736, 'SD', 'SDN', 'Sudán');
INSERT INTO `Country` VALUES (207, 752, 'SE', 'SWE', 'Suecia');
INSERT INTO `Country` VALUES (208, 756, 'CH', 'CHE', 'Suiza');
INSERT INTO `Country` VALUES (209, 740, 'SR', 'SUR', 'Surinam');
INSERT INTO `Country` VALUES (210, 744, 'SJ', 'SJM', 'Svalbard y Jan Mayen');
INSERT INTO `Country` VALUES (211, 764, 'TH', 'THA', 'Tailandia');
INSERT INTO `Country` VALUES (212, 158, 'TW', 'TWN', 'Taiwán');
INSERT INTO `Country` VALUES (213, 834, 'TZ', 'TZA', 'Tanzania');
INSERT INTO `Country` VALUES (214, 762, 'TJ', 'TJK', 'Tayikistán');
INSERT INTO `Country` VALUES (215, 86, 'IO', 'IOT', 'Territorio Británico del Océano Índico');
INSERT INTO `Country` VALUES (216, 260, 'TF', 'ATF', 'Territorios Australes Franceses');
INSERT INTO `Country` VALUES (217, 626, 'TL', 'TLS', 'Timor Oriental');
INSERT INTO `Country` VALUES (218, 768, 'TG', 'TGO', 'Togo');
INSERT INTO `Country` VALUES (219, 772, 'TK', 'TKL', 'Tokelau');
INSERT INTO `Country` VALUES (220, 776, 'TO', 'TON', 'Tonga');
INSERT INTO `Country` VALUES (221, 780, 'TT', 'TTO', 'Trinidad y Tobago');
INSERT INTO `Country` VALUES (222, 788, 'TN', 'TUN', 'Túnez');
INSERT INTO `Country` VALUES (223, 796, 'TC', 'TCA', 'Islas Turcas y Caicos');
INSERT INTO `Country` VALUES (224, 795, 'TM', 'TKM', 'Turkmenistán');
INSERT INTO `Country` VALUES (225, 792, 'TR', 'TUR', 'Turquía');
INSERT INTO `Country` VALUES (226, 798, 'TV', 'TUV', 'Tuvalu');
INSERT INTO `Country` VALUES (227, 804, 'UA', 'UKR', 'Ucrania');
INSERT INTO `Country` VALUES (228, 800, 'UG', 'UGA', 'Uganda');
INSERT INTO `Country` VALUES (229, 858, 'UY', 'URY', 'Uruguay');
INSERT INTO `Country` VALUES (230, 860, 'UZ', 'UZB', 'Uzbekistán');
INSERT INTO `Country` VALUES (231, 548, 'VU', 'VUT', 'Vanuatu');
INSERT INTO `Country` VALUES (232, 862, 'VE', 'VEN', 'Venezuela');
INSERT INTO `Country` VALUES (233, 704, 'VN', 'VNM', 'Vietnam');
INSERT INTO `Country` VALUES (234, 92, 'VG', 'VGB', 'Islas Vírgenes Británicas');
INSERT INTO `Country` VALUES (235, 850, 'VI', 'VIR', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO `Country` VALUES (236, 876, 'WF', 'WLF', 'Wallis y Futuna');
INSERT INTO `Country` VALUES (237, 887, 'YE', 'YEM', 'Yemen');
INSERT INTO `Country` VALUES (238, 262, 'DJ', 'DJI', 'Yibuti');
INSERT INTO `Country` VALUES (239, 894, 'ZM', 'ZMB', 'Zambia');
INSERT INTO `Country` VALUES (240, 716, 'ZW', 'ZWE', 'Zimbabue');
